const appname = "eMarche";
const appversion = "Version 1.0.0";
const credits = "@bouyaa62";
const email = "Email";
const emailHint = "admin@admin.com";
const password = "Password";
const passwordHint = "******";
const retypePassword = "Retype Password";
const name = "Name";
const nameHint = "Ayoub";
const forgetPass = "Forget Password";
const login = "Log in";
const singup = "Sign up";
const createNewAccount = "or, create a new account";
const loginWith = "Log in with";
const privacyPolicy = "Privacy Policy";
const loggedin = "Logged in successfully";
const loggedout = "Logged out successfully";
const termAndCondition = "Terms and Conditions";
const alreadyHaveAccount = "Already have an account? ";

const home = "Home",
    categories = "Categories",
    cart = "Cart",
    account = "Account";
const searchAnything = "Search anything...",
    todayDeal = "Today's Deal",
    flashSale = "Flash Sale",
    topSellers = "Top Sellers",
    brand = "Brand",
    topCategories = "Top Categories",
    womenDress = "Women Dress",
    girlsWatches = "Girls Watches",
    mobilePhone = "Mobile Phone",
    boysGlasses = "Boys Glasses",
    tShirts = "TShirts",
    girlsDress = "Girls Dress",
    featuredProduct = "Featured Product",
    featuredCategories = "Featured Categories";

const womenClothing = "Women Dress",
    menClothingFashion = "Men Clothing & Fashion",
    compAcess = "Computer & Accessories",
    automobile = "Automobiles",
    kidToys = "Kids & Toys",
    sports = "Sports",
    jewelery = "Jewelery",
    cellPhone = "Cellphone & Tab",
    furniture = "Furniture";

const video = "Video",
    reviews = "Reviews",
    seller = "Seller Policy",
    returnPolicy = "Return Policy",
    supportPolicy = "Support Policy",
    productsyoumaylike = "Products you may also like";

const logout = "Log out";

const wishlist = "My Wishlist",
    orders = "My Orders",
    message = "Messages",
    oldpass = "Old password",
    newpass = "New password";
